### PR TITLE
Web app manifest

### PR DESCRIPTION
**Pull request by Rudloff**
Hello,

This patch adds a web app manifest (see https://github.com/lesspass/lesspass/issues/26).

### CODE REVIEW

**Comment by guillaumevincent** [comment]
thank you
I try to push the modification during the week end

**Comment by guillaumevincent** [comment]
@Rudloff can you try the modification ?

**Comment by Rudloff** [comment]
I see you've moved the manifest file to dist. The paths are relative to this file so I updated my branch in order to fix them: https://github.com/lesspass/frontend/compare/master...Rudloff:feature/manifest
I also imported icons from lesspass/webextension as they work quite well on mobile.

**Comment by guillaumevincent** [comment]
@thank you @Rudloff 
I pushed your PR

Can I add you in the contributors of LessPass ?

**Comment by Rudloff** [comment]
Yes, of course you can 🙂

**Comment by edouard-lopez** [comment]
@Rudloff What is the expected behavior? Visiting the page several times doesn't do anything. 

### Env

I'm using: 
* Firefox Beta `49.0.2`
* on Android `6.0.1` (CyanoGenMod `13.0`). 

### Steps

**Firefox**
* open Firefox, click speed dial entry for Lesspass ;
* wait to load ;
* close tab ;
* repeat 2-3 times

Results: nothing.

**Browser** (chrome?)
* open Browser, type URL https://lesspass.com ;
* wait to load ;
* close tab ;
* repeat 2-3 times

Results: nothing.

**Comment by edouard-lopez** [comment]
The "Add to Home Screen" works but I got a warning icons

### Steps to reproduce

### step 01: tap the menu icon on the top-right
step 01: tap the menu icon on the top-right

### step 02: select "Page" entry from the menu
step 02: select "Page" entry from the menu

### step 03: select "Add to Home Screen"

step 03: select "Add to Home Screen"

### Home screen result
Home screen result

**Comment by Rudloff** [comment]
Firefox does not handle manifests correctly yet (see [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1234558)).
However, it should work correctly if you add to homescreen from Chrome.

As for the install banner that appears if you visit the page several times, it only works if the website has a registered service worker (among [some other criteria](https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android)).

**Pull request merged**
